### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by xuyuji9000** [coderbunker/aws-playground#4]
- [ ] Application with role collaboration
- [ ] Application logging
- [ ] Application monitoring
- [ ] Jenkins pipeline to Elastic Beanstalk
- [ ] ECS Cluster
- [ ] Jenkins Pipeline to ECS 
- [ ] First Notification with Coderbunker Wechat Bot
- [ ] Lambda Function

**Comment by xuyuji9000** [comment]
The goal is not clear.
